// <auto-generated />
using System;
using BlueRaven.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueRaven.Data.Migrations
{
    [DbContext(typeof(BRContext))]
    [Migration("20180905010104_AddFaviconUrl")]
    partial class AddFaviconUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("BlueRaven.Data.Models.Blog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ByLine");

                    b.Property<string>("Disclaimer");

                    b.Property<string>("FaviconUrl");

                    b.Property<string>("LocalUrl");

                    b.Property<string>("Theme");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = "blog1", ByLine = "Powered by Blue Raven", Disclaimer = "Read at your own risk!", LocalUrl = "https://localhost:5001", Theme = "Default", Title = "Blue Raven", Url = "https://example.com" }
                    );
                });

            modelBuilder.Entity("BlueRaven.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("BlogId");

                    b.Property<string>("Categories");

                    b.Property<string>("Content");

                    b.Property<string>("Excerpt");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Keywords");

                    b.Property<DateTime>("LastModified");

                    b.Property<DateTime>("PubDate");

                    b.Property<string>("Slug");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = 1, Author = "Me", BlogId = "blog1", Categories = "", Content = @"Bacon ipsum dolor amet doner drumstick swine prosciutto. Swine boudin chuck tongue flank beef venison. Turducken strip steak beef ribs boudin. Pastrami jowl pork loin tri-tip. Ham hock biltong buffalo, pork short ribs spare ribs turducken strip steak prosciutto swine porchetta venison bresaola tongue doner. Porchetta bresaola pork chop venison. Boudin picanha burgdoggen drumstick meatball pork chop cow cupim shoulder tenderloin turducken filet mignon.
Fatback sausage chicken spare ribs, rump pork chop picanha strip steak buffalo. Burgdoggen beef frankfurter, spare ribs hamburger pork loin alcatra pork belly doner ground round biltong. Strip steak short loin leberkas ball tip salami brisket drumstick spare ribs. Ham bacon buffalo bresaola, short loin cupim flank rump pastrami tenderloin porchetta venison ball tip burgdoggen t-bone. Swine hamburger pork prosciutto pig pork belly jerky venison flank shoulder bacon pancetta. Salami pork chop rump, biltong kielbasa filet mignon pig.
Ball tip burgdoggen bresaola pancetta. Biltong pork loin buffalo, hamburger flank beef ribs shankle pig ground round ball tip. Pork loin kevin beef ribs turducken, flank ham hock short loin cupim beef t-bone ribeye ground round pig fatback. Kevin salami beef swine. Flank pig burgdoggen sirloin.", Excerpt = "Bacon ipsum dolor amet doner drumstick swine prosciutto. Swine boudin chuck tongue flank beef venison. Turducken strip steak beef ribs boudin. Pastrami jowl pork loin tri-tip. Ham hock biltong buffalo, pork short ribs spare ribs turducken strip...", IsPublished = true, Keywords = "", LastModified = new DateTime(2018, 9, 5, 1, 1, 3, 919, DateTimeKind.Utc), PubDate = new DateTime(2018, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), Slug = "2018/7/6/first-post", Title = "First post" },
                        new { Id = 2, Author = "Me", BlogId = "blog1", Categories = "", Content = @"Spicy jalapeno ground round short loin pork chop, beef ribs t-bone meatball beef. Beef ribs tail filet mignon, drumstick sirloin kevin fatback jerky flank swine buffalo prosciutto. Short loin chuck capicola pastrami turkey bacon filet mignon. Pork chop pancetta beef boudin. Ball tip swine ground round tongue short ribs tenderloin pig landjaeger flank fatback shankle drumstick cupim.
Bresaola t-bone tri-tip chicken ham hock shankle brisket. Landjaeger shank doner meatball, tenderloin rump prosciutto frankfurter jerky. Filet mignon salami beef fatback beef ribs, andouille strip steak meatloaf prosciutto t-bone pork belly brisket ground round tail. Tenderloin jowl ribeye swine venison, short loin spare ribs short ribs burgdoggen pork chop shank shoulder. Hamburger bacon burgdoggen, turducken boudin ground round filet mignon flank shoulder. Pig meatloaf ham, hamburger turkey porchetta pastrami rump. Salami chicken porchetta, shoulder ham landjaeger t-bone turkey pancetta.
Shoulder boudin pork brisket, picanha meatball tongue sausage ball tip spare ribs venison flank leberkas burgdoggen pork belly. Flank spare ribs rump leberkas, beef ribs andouille ham hock tri-tip alcatra doner t-bone. Tongue cupim jowl, jerky chuck prosciutto chicken ball tip shank fatback buffalo doner flank. Beef ribs sausage t-bone landjaeger flank salami pork kevin beef bacon short ribs pork loin ham ball tip. Sausage beef buffalo, cupim kielbasa kevin turkey. Pork loin bresaola tri-tip pork chop jerky salami corned beef ball tip tail. Ham cow pig turkey, t-bone beef leberkas boudin shoulder burgdoggen prosciutto meatloaf pastrami tail.", Excerpt = "Spicy jalapeno ground round short loin pork chop, beef ribs t-bone meatball beef. Beef ribs tail filet mignon, drumstick sirloin kevin fatback jerky flank swine buffalo prosciutto. Short loin chuck capicola pastrami turkey bacon filet mignon. Pork...", IsPublished = true, Keywords = "", LastModified = new DateTime(2018, 9, 5, 1, 1, 3, 920, DateTimeKind.Utc), PubDate = new DateTime(2018, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Slug = "2018/7/13/next-post", Title = "Next post" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BlueRaven.Data.Models.Post", b =>
                {
                    b.HasOne("BlueRaven.Data.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
